#!/usr/bin/env bash

# Generated by Spellcaster ☱
# © 2023, Distinguished LLC. All rights reserved.

# Name: archConfig
# ID: 4b6c30f4-fbff-42a0-ba31-4874cbf54a5a
# Description: A spell to configure a new Arch instance
# Identity: topherludlow@protonmail.com

exec 3>&1
exec > >(tee -a spellcaster.log) 2>&1

start_time="$(date -u +%s)"
echo -en "\033[0;37m"
cat << "EOF"
 __                        
(_ ._  _ || _ _. __|_ _ ._ 
__)|_)(/_||(_(_|_> |_(/_|  
   |                       
EOF

echo -e "Name: archConfig"
echo -e "ID: 4b6c30f4-fbff-42a0-ba31-4874cbf54a5a"
echo -e "Description: A spell to configure a new Arch instance"
echo -e "Identity: topherludlow@protonmail.com"
echo -e "Converging 19 resources..."
converge=''
cycle=0
converged="$(printf "\xE2\x98\xB1%.0s "  $(seq 19))"
echo -en "\033[0m"

while [ "$converge" != "$converged" ] && [ $cycle -le 19 ]
  do
    converge=''
    if (id topher > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 User 'topher' should exist"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 User 'topher' should exist"
      echo -en "\033[0m"
      u_out=$(sudo useradd -m -p '$6$b4dZZN3tfiGwTEkG$Cl2ImbiCz3M8RYUZWuYo0zU0/.wBVPlO3pVntDl0WOlwnI9dmHTnBgoRghyadF0lSrpARhnlHbjYR2gt0iq971' topher)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -n "$(find /tmp/yay -name "yay-*-x86_64.pkg.tar.zst" -not -name "*debug*")" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Yay package should be built"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Yay package should be built"
      echo -en "\033[0m"
      u_out=$(su - topher -c "cd /tmp/yay && makepkg -s")
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (grep -A1 '^\[multilib\]$' /etc/pacman.conf | grep -q '^Include = /etc/pacman.d/mirrorlist$' > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 multilib should be enabled in pacman conf"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 multilib should be enabled in pacman conf"
      echo -en "\033[0m"
      u_out=$(sudo sed -i '/^#\[multilib\]/{N;s/^#\[multilib\]\n#Include/[multilib]\nInclude/}' /etc/pacman.conf && sudo pacman -Sy --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (sudo systemctl is-active dhcpcd@$(ip -o link show | grep -E 'eth|enp|eno|ens' | head -n 1 | awk -F': ' '{print $2}').service > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 dhcpcd@ETHERNET.service should be started"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 dhcpcd@ETHERNET.service should be started"
      echo -en "\033[0m"
      u_out=$(sudo systemctl start dhcpcd@$(ip -o link show | grep -E 'eth|enp|eno|ens' | head -n 1 | awk -F': ' '{print $2}').service)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -n "$(find /tmp/spotify -name "spotify-*-x86_64.pkg.tar.zst" -not -name "*debug*")" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Spotify package should be built"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Spotify package should be built"
      echo -en "\033[0m"
      u_out=$(su - topher -c "cd /tmp/spotify && makepkg -s --skippgpcheck")
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (sudo systemctl is-enabled dhcpcd@$(ip -o link show | grep -E 'eth|enp|eno|ens' | head -n 1 | awk -F': ' '{print $2}').service > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 dhcpcd@ETHERNET.service should be enabled"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 dhcpcd@ETHERNET.service should be enabled"
      echo -en "\033[0m"
      u_out=$(sudo systemctl enable dhcpcd@$(ip -o link show | grep -E 'eth|enp|eno|ens' | head -n 1 | awk -F': ' '{print $2}').service)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (grep -qF -x "127.0.0.1 localhost" /etc/hosts && grep -qF -x "::1 localhost" /etc/hosts > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Hosts should be set in /etc/hosts"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Hosts should be set in /etc/hosts"
      echo -en "\033[0m"
      u_out=$(echo -e "127.0.0.1 localhost
::1 localhost
" | sudo tee -a /etc/hosts)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q lib32-nvidia-utils > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 32 bit Nvidia drivers should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 32 bit Nvidia drivers should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S lib32-nvidia-utils --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q dhcpcd > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 dhcpcd should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 dhcpcd should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S dhcpcd --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (grep -qw "topherDesktop" /etc/hostname > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Hostname should be set to topherDesktop"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Hostname should be set to topherDesktop"
      echo -en "\033[0m"
      u_out=$(echo "topherDesktop" | sudo tee /etc/hostname)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q git > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Git should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Git should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S git --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q yay > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Yay should be installed and removed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Yay should be installed and removed"
      echo -en "\033[0m"
      u_out=$((find /tmp/yay -name "yay-*.pkg.tar.zst" -not -name "*debug*" | xargs pacman -U --noconfirm) && rm -r /tmp/yay)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -f /tmp/yay/PKGBUILD && grep "^depends\|^makedepends" /tmp/yay/PKGBUILD | sed -e "s/^depends=(//g" -e "s/^makedepends=(//g" -e "s/)$//g" | tr "'" " " | awk '{print $1}' | sed 's/>.*$//' | xargs pacman -Q > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Yay dependencies should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Yay dependencies should be installed"
      echo -en "\033[0m"
      u_out=$(grep "^depends\|^makedepends" /tmp/yay/PKGBUILD | sed -e "s/^depends=(//g" -e "s/^makedepends=(//g" -e "s/)$//g" | tr "'" " " | awk '{print $1}' | sed 's/>.*$//' | xargs pacman -S --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -f /tmp/yay/PKGBUILD > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Yay repo should be cloned to /tmp/yay"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Yay repo should be cloned to /tmp/yay"
      echo -en "\033[0m"
      u_out=$(git clone https://aur.archlinux.org/yay.git /tmp/yay && chown -R topher:topher /tmp/yay)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q base-devel > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 base-devel should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 base-devel should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S base-devel --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -f /tmp/spotify/PKGBUILD && grep "^depends\|^makedepends" /tmp/spotify/PKGBUILD | sed -e "s/^depends=(//g" -e "s/^makedepends=(//g" -e "s/)$//g" | tr "'" " " | tr -s ' ' '\n' | sed '/^$/d' | sed 's/>.*$//' | xargs pacman -Q > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Spotify dependencies should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Spotify dependencies should be installed"
      echo -en "\033[0m"
      u_out=$(grep "^depends\|^makedepends" /tmp/spotify/PKGBUILD | sed -e "s/^depends=(//g" -e "s/^makedepends=(//g" -e "s/)$//g" | tr "'" " " | tr -s ' ' '\n' | sed '/^$/d' | sed 's/>.*$//' | xargs pacman -S --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (locale --all-locales | grep -q "en_US.utf8" > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 en_US.UTF-8 locale should be generated"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 en_US.UTF-8 locale should be generated"
      echo -en "\033[0m"
      u_out=$(sudo sed -i 's/^#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && sudo locale-gen)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (test -f /tmp/spotify/PKGBUILD > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Spotify PKGBUILD should be downloaded"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Spotify PKGBUILD should be downloaded"
      echo -en "\033[0m"
      u_out=$(su - topher -c "cd /tmp && yay -G spotify")
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    if (pacman -Q steam > /dev/null)
    then
      c_exit=0
      echo -en "\033[0;32m"
      echo -e "  \xE2\x9C\x93 Steam should be installed"
      echo -en "\033[0m"
      u_exit=1
    else
      c_exit=1
      echo -en "\033[0;31m"
      echo -e "  \xE2\x9C\x97 Steam should be installed"
      echo -en "\033[0m"
      u_out=$(sudo pacman -S steam --noconfirm)
      u_exit=$?
    fi
    r_exit=$?
    # echo "$r_exit$c_exit$u_exit"
    # set any non zero value as 1 for read 
    if [ $r_exit -ne 0 ]; then r_exit=1; fi
    case "$r_exit$c_exit$u_exit" in
    000) converge="$converge$(printf "\xE2\x98\xB0") ";;
    001) converge="$converge$(printf "\xE2\x98\xB1") ";;
    010) converge="$converge$(printf "\xE2\x98\xB2") ";;
    011) converge="$converge$(printf "\xE2\x98\xB3") ";;
    100) converge="$converge$(printf "\xE2\x98\xB4") ";;
    101) converge="$converge$(printf "\xE2\x98\xB5") ";;
    110) converge="$converge$(printf "\xE2\x98\xB6") ";;
    111) converge="$converge$(printf "\xE2\x98\xB7") ";;
    esac

    echo -e "cycle $cycle"
    echo -e "$converge"
    echo -e "$converged"
    cycle=$(( cycle+1 ))
done

end_time="$(date -u +%s)"

  echo -en "\033[1;33m"
  echo -e "* The Spellcaster free tier includes up to 10 trigraphs. You are at 19 trigraphs and should sign up for an individual plan here https://spellcaster.sh/pricing.\n"
  echo -en "\033[0m"

if [ "$converge" = "$converged" ]
then
  elapsed="$((end_time-start_time))"
  echo -en "\033[0;37m"
  echo -e "Spellcaster converged in $cycle cycles"
  echo -e "Convergence time: $elapsed seconds"
  (( RANDOM%20 == 0 )) && cat <<-EOF | base64 -d | gzip -dc
H4sIAAAAAAAAA7VX7W7aUAz9z1ODhkpQVyFt09SqanM/ENG0VatGxYfowrvcJ5l9bEMCBAJ0klWF
5N7r4+Nj+za5brrYIplLcQzDz0uP6lyyLZDvWXJ5co/JDc3oeZXCmj8RLP+/cRAIv06u10zSnQGa
tEdzJo6TINiyFIoU+8yQ0tPn9PkyxaIJ2Tk4AsVKID61WHzPK+MclAyZnvgzxTL5v/zyWhwMYmDP
sJ3gai8XWL8CoBIsUgBLxbfHSmscUc7daPPIYtMsuxzYm0rW+CvZl/NxcIEgoLBTq00mrCA7/qaN
i2YcQfy9sdCYVSHj1qq0SaqZLXhA0GuT6oTV2lw+nQbfJRyfTEF7GyosEe8epo7pC745o48p9mot
8rpGWTtEE/oZXjaYBEd8Z9rjnkkKwhJJWelLP4O+yP6A7brx1+/6NZR2Ts6p8SNN1r4jTty8w564
kB7wW3ZSUu5UAZwgaD6s8DdLcYU4ZsoZtQT29NsoNF49tvscrNxb2yD1/EhublERiFtUdS76eDA1
vTBjTABtGzNVbsTFEmYA1NXF7msKE/7KZwlKVDW1S8Khcpak0II+G3eOgs90UB7n5YUXeyG+ptNM
617VhEkWXplSdjOor6SUDVNcWmejiEdonfVSoo0ElJN7g+TOrAJ2+1BD3fIcARNCrITOI8MW+HfE
sarsKgFuui2E6FSMfOCSWWENHG4nh3Bw9eaYTGs8v2tM8Sn5OURAsKbJvSGmKdj+hmdK1jO4HKfw
xjOFw1hoIw+IhOR1qIsc5GMB+WCuksttEENryRXyY3eXqtqyDbUFnkkuT9shdQqHcRBfMZwyvUxw
NJtOQJVCfDxXOuwU4q12HWdK7EFAE+jsrHkrNSwScX3sL9QfFbD44G7xbHEjQWFmwyW3xQstKBGH
F4W2x6Gl6NF/5JR1Ja9H+r1g6qnOWGEe4qDk/lJM5+EglXgMbukNQqnkq3FLNbMFGtQAoi742kBE
XoTD0LBgl5omL81qfBTBWFuqTAPuhGvltdna3D8ye5AakVkzqXTYDQK5qed7IshOerno/wYHIbNg
K/demZenb9Efi0ONBpNchsvtTLnIrsQh9gF3pc4/2V8NtlgOAAA=
EOF
  echo -en "\033[0m"
  exit 0
else
  elapsed="$((end_time-start_time))"
  echo -en "\033[0;37m"
  echo -e "Spellcaster failed to converge in $cycle cycles"
  echo -e "Convergence time: $elapsed seconds"
  echo -en "\033[0m"
  exit 1
fi
